### ISSUE TITLE
Query Database

### ISSUE THREAD

**Issue by Thenewchicken55** [gmccannon/ISPProject#2]
For now, the code can read an array of articles and display it. We need to somehow query the database (or dataset) instead and get data. Note, the database is not implemented yet I don't think.

```javascript
let sampleArticles: NewsArticle[] = [
  {
    title: "Article 1",
    subtitle: "Subtitle 1",
    content: "Content 1",
  },
  {
    title: "Article 2",
    subtitle: "Subtitle 2",
    content: "Content 2",
  },
  {
    title: "Article 3",
    subtitle: "Subtitle 3",
    content: "Content 3",
  },
];
```
![image](https://github.com/user-attachments/assets/b9742181-2e5b-4b2d-95b4-ee37ae53b20d)

**Comment by gmccannon** [comment]
The endpoint is something along the lines of this:
https://newsapi.org/v2/{{type}}?q=&from=&sortBy=&apiKey=

type: can be" top-headlines" or "everything", as an example
q: refers to content in the title (ie 'apple' would return all articles with apple in the title)
from: refers to a date, 2024-11-20 for example
sortBy: self explanatory, popularity and date are to options
apiKey: the api key

i think the mongoose type should look something like:

const newsApiRequestSchema = new mongoose.Schema({
  type: {
    type: String,
    required: true,
    enum: ['top-headlines', 'everything'], // im pretty sure it can only be these values?????
  },
  q: {
    type: String,
  },
  from: {
    type: Date,
  },
  sortBy: {
    type: String,
    enum: ['popularity', 'date'], // there are more options then this we can add later
  },
  apiKey: {
    type: String,
    required: true,
  },
});

**Comment by Thenewchicken55** [comment]
Sounds good. Feel free to make any commits u want. 
Just to confirm, So are we querying news and storing it in db? I think that works well.

**Comment by gmccannon** [comment]
oops, i just realized you were referring to the news article type, not the request

This is what i found as a suggestion on newsapi:

type NewsArticle = {
  source: {
    id: string | null;
    name: string;
  };
  author: string | null;
  title: string;
  description: string | null;
  url: string;
  urlToImage: string | null;
  publishedAt: string;
  content: string | null;
};
