### ISSUE TITLE
Implement Stocks UI 

### ISSUE THREAD

**Issue by Thenewchicken55** [gmccannon/ISPProject#4]
Check `stocks` branch. It has an API call. 
- We need to make it prettier
- Optional implementation: 
  - User puts in stock name
  - Query for that stock
  - Store stock `name`, `price`, and `date` in database
  - Show user query histories on page

**Comment by gmccannon** [comment]
looks good, as for styling I can handle using material what whatever other component library we decide to use

**Comment by Thenewchicken55** [comment]
I think we're going to skip doing this
